### ISSUE TITLE
New files give me this, while the old files work fine. Help?

### ISSUE THREAD

**Issue by uzbekki** [j-e-k/poketrainer#133]
Traceback (most recent call last):
  File "pokecli.py", line 140, in <module>
    main()
  File "pokecli.py", line 102, in main
    config = init_config()
  File "pokecli.py", line 64, in init_config
    load.update(json.load(data))
  File "C:\Python27\lib\json\__init__.py", line 291, in load
    **kw)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 43 column 41 (char 1129)

**Comment by xezero** [comment]
Did your configuration file change? For some reason the new code doesn't recognize your previous config.json file unless you modify the config file and try to run it again.

**Comment by uzbekki** [comment]
I just took all new, edited the new conf and everything, cos I had like super old version

**Comment by j-e-k** [comment]
Not sure what you mean....Is it still not working for you? That error is due to malformed json. Use https://jsonformatter.curiousconcept.com/ to make sure your config is valid 😄

**Comment by j-e-k** [comment]
Reopen if you still have issues. Thanks
