### ISSUE TITLE
Python fails on load

### ISSUE THREAD

**Issue by HibikiFox** [j-e-k/poketrainer#162]
```
Traceback (most recent call last):
  File "pokecli.py", line 129, in <module>
    main()
  File "pokecli.py", line 95, in main
    config = init_config()
  File "pokecli.py", line 65, in init_config
    load.update(json.load(data))
  File "D:\Python27\lib\json\__init__.py", line 291, in load
    **kw)
  File "D:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "D:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Python27\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

```

**Comment by stef264** [comment]
Maybe your config.json is malformed.
Paste your config here: https://jsonformatter.curiousconcept.com/

**Comment by HibikiFox** [comment]
Yup ty that fixed it

I was trying to use       "CATCH_POKEMON": ture,

But I can't figure our where to insert it into the confgi.json file.

 thoughts?

**Comment by stef264** [comment]
"CATCH_POKEMON" is only available in the develop branch (i think).
If your using the develop bot you can insert it after a default option.

Example: `"SPIN_ALL_FORTS": true,
"STAY_WITHIN_PROXIMITY": 9999,
"CATCH_POKEMON": true,`

**Comment by HibikiFox** [comment]
Never mind it fit into the space below pokemon evolution,
