### ISSUE TITLE
Crash after spinning

### ISSUE THREAD

**Issue by GUICenter** [j-e-k/poketrainer#182]
This seems to only happen when "SPIN_ALL_FORTS": true when it's false it does not happen. 

2016-07-27 21:17:35,980 [    pgoapi] [ INFO] Fort Spinned, XP +50, 3x POKE_BALL (http://maps.google.com/maps?q=removed)
2016-07-27 21:17:36,211 [    pgoapi] [ INFO] Could not spin fort http://maps.google.com/maps?q=, Error id:removed 3
2016-07-27 21:17:37,454 [    pgoapi] [ INFO] No nearby pokemon
2016-07-27 21:17:40,273 [    pgoapi] [ INFO] =================================
2016-07-27 21:17:40,273 [    pgoapi] [ INFO] On my way to the next fort! :) Traveled 319.01 meters of 124.56
2016-07-27 21:17:40,273 [    pgoapi] [ INFO] Travel Link: https://www.google.com/maps/dir/removed
2016-07-27 21:17:40,414 [    pgoapi] [ INFO] Player Info: , Currencies: POKECOIN: NA,STARDUST: 39608, Pokemon Caught in this run: 2
2016-07-27 21:17:40,624 [    pgoapi] [ INFO] Nearest fort distance is 0.0
2016-07-27 21:17:40,832 [   pokecli] [ERROR] Error in main loop, restarting %s
Traceback (most recent call last):
  File "C:\Users\ilana\Downloads\pgoapi-master\pokecli.py", line 121, in main
    api.main_loop()
  File "C:\Users\ilana\Downloads\pgoapi-master\pgoapi\pgoapi.py", line 846, in main_loop
    self.spin_all_forts_visible()
  File "C:\Users\ilana\Downloads\pgoapi-master\pgoapi\pgoapi.py", line 389, in spin_all_forts_visible
    map(lambda x: "via:%f,%f" % (x[0]['latitude'], x[0]['longitude']), destinations[1:]))
  File "C:\Users\ilana\Downloads\pgoapi-master\pgoapi\pgoapi.py", line 297, in walk_to
    self.spin_nearest_fort()
  File "C:\Users\ilana\Downloads\pgoapi-master\pgoapi\pgoapi.py", line 333, in spin_nearest_fort
    fort_distance=nearest_fort_dis)
  File "C:\Users\ilana\Downloads\pgoapi-master\pgoapi\pgoapi.py", line 348, in fort_search_pgoapi
    for item in res['items_awarded']:
KeyError: 'items_awarded'

**Comment by sftwninja** [comment]
This will be fixed by #175

**Comment by j-e-k** [comment]
Should be fixed now. Open another if you are still having this problem
