### ISSUE TITLE
jinja2.exceptions.UndefinedError

### ISSUE THREAD

**Issue by panjitianda** [j-e-k/poketrainer#191]
Just pull new
and gettin this

jinja2.exceptions.UndefinedError
UndefinedError: 'dict object' has no attribute 'level_xp'

`Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/test/poketrainer/web.py", line 54, in inventory
    return render_template('pokemon.html', pokemons=pokemons, player=player,currency="{:,d}".format(currency), candy=candy,latlng=latlng)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/test/poketrainer/templates/pokemon.html", line 49, in top-level template code
    {{ (player["level_xp"] / player["goal_xp"] * 100)|int }}%
UndefinedError: 'dict object' has no attribute 'level_xp'`

**Comment by j-e-k** [comment]
Not seeing this. What branch are you on? Can anyone else reproduce?

**Comment by j-e-k** [comment]
https://github.com/j-e-k/poketrainer/blob/master/web.py#L58

should ensure this works

**Comment by panjitianda** [comment]
done, i;ve modify the web.py so its missmacth with the template

**Comment by j-e-k** [comment]
So it works for you now?
