### ISSUE TITLE
problem since update

### ISSUE THREAD

**Issue by ytroch** [j-e-k/poketrainer#199]
since doing a git pull about two hours ago i keep running into:
```
python pokecli.py -i 1 -l 'Central Park'
Traceback (most recent call last):
  File "pokecli.py", line 129, in <module>
    main()
  File "pokecli.py", line 95, in main
    config = init_config()
  File "pokecli.py", line 65, in init_config
    load.update(json.load(data))
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 40 column 208 (char 1338)
```

(which worked untill yesterday)

**Comment by DeOrthodox** [comment]
C:\Python27\python pokecli.py -i 0
Traceback (most recent call last):
  File "pokecli.py", line 129, in <module>
    main()
  File "pokecli.py", line 95, in main
    config = init_config()
  File "pokecli.py", line 65, in init_config
    load.update(json.load(data))
  File "C:\Python27\lib\json\__init__.py", line 291, in load
    **kw)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 18 column 7 (char 513)

is what im getting

**Comment by ytroch** [comment]
i think i got that first, then copied the old config.json settings into the config.json.example and then renamed it to config.json. 
so i think i might have ended up with a crippled config...
let me test for a minute...

**Comment by ytroch** [comment]
UPDATE & Fix

overwrite your custom config with the new files and make the changes again (if needed)
