### ISSUE TITLE
web.py KeyError: 'prev_level_xp'

### ISSUE THREAD

**Issue by grAND1337** [j-e-k/poketrainer#214]
I'm trying to view the web UI site at http://127.0.0.1:5000/censored@gmail.com/pokemon but I get these errors:

![screencapture-127-0-0-1-5000-pgojesper-gmail-com-pokemon-1469730541358](https://cloud.githubusercontent.com/assets/20709778/17224870/06bdb3f2-5503-11e6-99bb-a6ff3af6fe9f.png)

`Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/Flask-0.11.1-py2.7.egg/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Python/2.7/site-packages/Flask-0.11.1-py2.7.egg/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Library/Python/2.7/site-packages/Flask-0.11.1-py2.7.egg/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/Flask-0.11.1-py2.7.egg/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/Flask-0.11.1-py2.7.egg/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/Flask-0.11.1-py2.7.egg/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/Flask-0.11.1-py2.7.egg/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/Flask-0.11.1-py2.7.egg/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Applications/XAMPP/xamppfiles/htdocs/poketrainer-master/web.py", line 58, in inventory
    player['level_xp'] = player['experience']-player['prev_level_xp']
KeyError: 'prev_level_xp'`

Am I missing some required dependency or something? The terminal client works fine.
Please ignore the fact I placed the directory in my XAMPP htdocs hehe (if this isn't the cause of the error, that is)...

**Comment by grAND1337** [comment]
It seems it was all because the file in data_dumps didn't have the required permissions, changed permissions to read & write and no more errors...! 😳
