### ISSUE TITLE
Web UI Broke since last merge

### ISSUE THREAD

**Issue by HibikiFox** [j-e-k/poketrainer#218]
the Web Ui is broken, here is the copy/paste from the web view and the console log

webpage
```
KeyError
KeyError: 'hourly_exp'

Traceback (most recent call last)
File "D:\Python27\lib\site-packages\flask\app.py", line 2000, in __call__
return self.wsgi_app(environ, start_response)
File "D:\Python27\lib\site-packages\flask\app.py", line 1991, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "D:\Python27\lib\site-packages\flask\app.py", line 1567, in handle_exception
reraise(exc_type, exc_value, tb)
File "D:\Python27\lib\site-packages\flask\app.py", line 1988, in wsgi_app
response = self.full_dispatch_request()
File "D:\Python27\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
rv = self.handle_user_exception(e)
File "D:\Python27\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "D:\Python27\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
rv = self.dispatch_request()
File "D:\Python27\lib\site-packages\flask\app.py", line 1625, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "D:\Hibiki\Downloads\pogo bots\pgoapi-master\poketrainer-develop\web.py", line 59, in inventory
player['hourly_exp'] = data["hourly_exp"]
KeyError: 'hourly_exp'
```

Console

```
127.0.0.1 - - [28/Jul/2016 14:31:09] "GET /%UserName%/pokemon HTTP/1.1" 500 -
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\flask\app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "D:\Python27\lib\site-packages\flask\app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\%UserProfile%\Downloads\pogo bots\pgoapi-master\poketrainer-develop\web.py", line 59, in inventory
    player['hourly_exp'] = data["hourly_exp"]
KeyError: 'hourly_exp'
127.0.0.1 - - [28/Jul/2016 14:31:09] "GET /%UserName%/pokemon?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [28/Jul/2016 14:31:09] "GET /%UserName%/pokemon?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [28/Jul/2016 14:31:09] "GET /%UserName%/pokemon?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [28/Jul/2016 14:31:10] "GET /%UserName%/pokemon?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
127.0.0.1 - - [28/Jul/2016 14:31:10] "GET /%UserName%/pokemon?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -

```

**Comment by j-e-k** [comment]
Can you check the contents of the data dump file, does there exist 

```{
  "hourly_exp": 432112.142392317, 
```
at the top?

**Comment by HibikiFox** [comment]
@j-e-k  where is the file?

Also the issue resolved itself, I think because I started the web server and the the bot. it had NO value until the bot spun a stop or caught something so the Hourly_exp had nothing in it

**Comment by j-e-k** [comment]
Yep that is why, I will change it to have a default value to prevent crash,
