### ISSUE TITLE
Error in main loop `GET_MAP_OBJECTS`

### ISSUE THREAD

**Issue by HibikiFox** [j-e-k/poketrainer#225]
Not sure what caused this error

```
2016-07-28 16:43:25,239 [   pokecli] [ERROR] Error in main loop, restarting %s
Traceback (most recent call last):
  File "pokecli.py", line 121, in main
    api.main_loop()
  File "D:\%Path%\Downloads\pogo bots\pgoapi-master\poketrainer-develop\pgoapi\pgoapi.py", line 921, in main_loop
    self.spin_all_forts_visible()
  File "D:\%Path%\Downloads\pogo bots\pgoapi-master\poketrainer-develop\pgoapi\pgoapi.py", line 459, in spin_all_forts_visible
    map(lambda x: "via:%f,%f" % (x[0]['latitude'], x[0]['longitude']), destinations[1:]))
  File "D:\%Path%\Downloads\pogo bots\pgoapi-master\poketrainer-develop\pgoapi\pgoapi.py", line 376, in walk_to
    while self.catch_near_pokemon() and catch_attempt <= self.max_catch_attempts:
  File "D:\%Path%\Downloads\pogo bots\pgoapi-master\poketrainer-develop\pgoapi\pgoapi.py", line 495, in catch_near_pokemon
    map_cells = self.nearby_map_objects()['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'GET_MAP_OBJECTS'
```

Also, in effort to help prevent detection is there a way to make it restart on it's last position, as of now it reverts to the starting Location, and in some cases might not be bad, other times you can jump KM at a time

**Comment by j-e-k** [comment]
I added last position reset to development with a quick hack see #241 

error is likely soft ban/server issues

**Comment by HibikiFox** [comment]
Still occurring, though less frequent
```
2016-07-29 21:30:05,401 [   pokecli] [ERROR] Error in main loop 'GET_MAP_OBJECTS', restarting at location: (39.54835262692445, -105.00084969203148, 0)
Traceback (most recent call last):
  File "pokecli.py", line 158, in main
    api.main_loop()
  File "D:\Users\Jason\Downloads\poketrainer-develop\poketrainer-develop\pgoapi\pgoapi.py", line 996, in main_loop
    self.spin_all_forts_visible()
  File "D:\Users\Jason\Downloads\poketrainer-develop\poketrainer-develop\pgoapi\pgoapi.py", line 484, in spin_all_forts_visible
    map(lambda x: "via:%f,%f" % (x[0]['latitude'], x[0]['longitude']), destinations[1:]))
  File "D:\Users\Jason\Downloads\poketrainer-develop\poketrainer-develop\pgoapi\pgoapi.py", line 401, in walk_to
    while self.catch_near_pokemon() and catch_attempt <= self.max_catch_attempts:
  File "D:\Users\Jason\Downloads\poketrainer-develop\poketrainer-develop\pgoapi\pgoapi.py", line 521, in catch_near_pokemon
    map_cells = self.nearby_map_objects()['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'GET_MAP_OBJECTS'
```

**Comment by j-e-k** [comment]
Hopefully fixed (again) by a pr I just merged in....
