### ISSUE TITLE
Error in main loop 'RECYCLE_INVENTORY_ITEM'

### ISSUE THREAD

**Issue by HibikiFox** [j-e-k/poketrainer#227]
```
2016-07-28 16:57:22,953 [    pgoapi] [ INFO] Recycling Item_ID 201, item count 1
2016-07-28 16:57:23,071 [   pokecli] [ERROR] Error in main loop, restarting %s
Traceback (most recent call last):
  File "pokecli.py", line 121, in main
    api.main_loop()
  File "D:\%path%\Downloads\pogo bots\pgoapi-master\poketrainer-develop\pgoapi\pgoapi.py", line 921, in main_loop
    self.spin_all_forts_visible()
  File "D:\%path%\Downloads\pogo bots\pgoapi-master\poketrainer-develop\pgoapi\pgoapi.py", line 459, in spin_all_forts_visible
    map(lambda x: "via:%f,%f" % (x[0]['latitude'], x[0]['longitude']), destinations[1:]))
  File "D:\%path%\Downloads\pogo bots\pgoapi-master\poketrainer-develop\pgoapi\pgoapi.py", line 373, in walk_to
    self.spin_nearest_fort()
  File "D:\%path%\Downloads\pogo bots\pgoapi-master\poketrainer-develop\pgoapi\pgoapi.py", line 399, in spin_nearest_fort
    self.walk_to_fort(destinations[0], directly=True)
  File "D:\%path%\Downloads\pogo bots\pgoapi-master\poketrainer-develop\pgoapi\pgoapi.py", line 469, in walk_to_fort
    self.walk_to((fort['latitude'], fort['longitude']), directly=directly)
  File "D:\%path%\Downloads\pogo bots\pgoapi-master\poketrainer-develop\pgoapi\pgoapi.py", line 369, in walk_to
    self.heartbeat()
  File "D:\%path%\Downloads\pogo bots\pgoapi-master\poketrainer-develop\pgoapi\pgoapi.py", line 280, in heartbeat
    self.log.debug(self.cleanup_inventory(self.inventory.inventory_items))
  File "D:\%path%\Downloads\pogo bots\pgoapi-master\poketrainer-develop\pgoapi\pgoapi.py", line 571, in cleanup_inventory
    'RECYCLE_INVENTORY_ITEM']
KeyError: 'RECYCLE_INVENTORY_ITEM'
```

**Comment by j-e-k** [comment]
error is likely soft ban/server issues

Let me know if you are still getting it...
