### ISSUE TITLE
Error in main loop 'RELEASE_POKEMON'

### ISSUE THREAD

**Issue by HibikiFox** [j-e-k/poketrainer#229]
```
2016-07-28 17:15:42,743 [   pokecli] [ERROR] Error in main loop, restarting %s
Traceback (most recent call last):
  File "pokecli.py", line 121, in main
    api.main_loop()
  File "D:\%path%\Downloads\pogo bots\pgoapi-master\poketrainer-develop\pgoapi\pgoapi.py", line 945, in main_loop
    self.spin_all_forts_visible()
  File "D:\%path%\Downloads\pogo bots\pgoapi-master\poketrainer-develop\pgoapi\pgoapi.py", line 473, in spin_all_forts_visible
    map(lambda x: "via:%f,%f" % (x[0]['latitude'], x[0]['longitude']), destinations[1:]))
  File "D:\%path%\Downloads\pogo bots\pgoapi-master\poketrainer-develop\pgoapi\pgoapi.py", line 387, in walk_to
    self.spin_nearest_fort()
  File "D:\%path%\Downloads\pogo bots\pgoapi-master\poketrainer-develop\pgoapi\pgoapi.py", line 413, in spin_nearest_fort
    self.walk_to_fort(destinations[0], directly=True)
  File "D:\%path%\Downloads\pogo bots\pgoapi-master\poketrainer-develop\pgoapi\pgoapi.py", line 483, in walk_to_fort
    self.walk_to((fort['latitude'], fort['longitude']), directly=directly)
  File "D:\%path%\Downloads\pogo bots\pgoapi-master\poketrainer-develop\pgoapi\pgoapi.py", line 383, in walk_to
    self.heartbeat()
  File "D:\%path%\Downloads\pogo bots\pgoapi-master\poketrainer-develop\pgoapi\pgoapi.py", line 299, in heartbeat
    self.cleanup_pokemon(self.inventory.inventory_items)
  File "D:\%path%\Downloads\pogo bots\pgoapi-master\poketrainer-develop\pgoapi\pgoapi.py", line 648, in cleanup_pokemon
    self.do_release_pokemon(pokemon)
  File "D:\%path%\Downloads\pogo bots\pgoapi-master\poketrainer-develop\pgoapi\pgoapi.py", line 618, in do_release_pokemon
    release_res = self.call()['responses']['RELEASE_POKEMON']
KeyError: 'RELEASE_POKEMON'

**Comment by joychugh** [comment]
hmm i guess sometime the server doesn't send the data as expected. we have to cleanup the code to expect bad response in places. I have seen it mostly happening for map objects maybe there was a server error that causes it. I think its very rare and the bot restarts the main loop again if there is an error.

**Comment by j-e-k** [comment]
Hopefully this has been fixed by one of the many PRs to improve error handling. Reopen if you are still seeing it on develop
