### ISSUE TITLE
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed

### ISSUE THREAD

**Issue by UnacceptableUse** [j-e-k/poketrainer#230]
Happens on every start: 
```
2016-07-29 00:22:30,421 [   pokecli] [ERROR] Error in main loop, restarting %s
Traceback (most recent call last):
  File "pokecli.py", line 121, in main
    api.main_loop()
  File "C:\Users\Peter\Documents\DOCUMENTS\Programs\PokeTrainer\pgoapi\pgoapi.py", line 846, in main_loop
    self.spin_all_forts_visible()
  File "C:\Users\Peter\Documents\DOCUMENTS\Programs\PokeTrainer\pgoapi\pgoapi.py", line 389, in spin_all_forts_visible
    map(lambda x: "via:%f,%f" % (x[0]['latitude'], x[0]['longitude']), destinations[1:]))
  File "C:\Users\Peter\Documents\DOCUMENTS\Programs\PokeTrainer\pgoapi\pgoapi.py", line 264, in walk_to
    self.experimental and self.spin_all_forts, waypoints)
  File "C:\Users\Peter\Documents\DOCUMENTS\Programs\PokeTrainer\pgoapi\location.py", line 26, in get_route
    optimize_waypoints=True, waypoints=waypoints)
  File "C:\Python27\lib\site-packages\gmaps\directions.py", line 62, in directions
    return self._make_request(self.DIRECTIONS_URL, parameters, "routes")
  File "C:\Python27\lib\site-packages\gmaps\client.py", line 76, in _make_request
    raw_response = requests.get(url, params=parameters)
  File "C:\Python27\lib\site-packages\requests\api.py", line 71, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 477, in send
    raise SSLError(e, request=request)
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
```

**Comment by sftwninja** [comment]
Can you run this for me from the command line? `python -c "from requests.utils import DEFAULT_CA_BUNDLE_PATH; print(DEFAULT_CA_BUNDLE_PATH)"`

**Comment by UnacceptableUse** [comment]
C:\Python27\lib\site-packages\certifi\cacert.pem

**Comment by sftwninja** [comment]
Can you run `pip install -U certifi` and try re-running the bot and show me what happens?

**Comment by UnacceptableUse** [comment]
Requirement already up-to-date: certifi in c:\python27\lib\site-packages

I've just figured out that it only happens with USE_GOOGLE turned on, does
that help?

**Comment by sftwninja** [comment]
That helps a bit. I have kind of a theory what's going on, but some few additional points would help.

Run `python --version`, paste the result.
Run `pip freeze` and paste the result.
And are you behind a VPN or a proxy? Are you on a university internet or a cooperative residential internet agreement or your own private internet connection?

**Comment by UnacceptableUse** [comment]
r>python --version
Python 2.7.9

>pip freeze
Flask==0.11.1
MarkupSafe==0.23
SimpleWebSocketServer==0.1.0
Werkzeug==0.11.10
backports-abc==0.4
backports.ssl-match-hostname==3.5.0.1
certifi==2016.2.28
click==6.6
decorator==4.0.4
expiringdict==1.1.3
future==0.15.2
geopy==1.11.0
gpsoauth==0.3.0
ipython==3.2.0
itsdangerous==0.24
jinja2==2.7.1
leapcast==0.1.3
numpy==1.9.2
pgoapi==1.1.0
praw==3.3.0
protobuf==3.0.0b4
pycryptodomex==3.4.2
pyproj==1.9.5.1
pyreadline==2.0
python-gmaps==0.3.1
pytz==2016.6.1
requests==2.10.0
s2sphere==0.2.4
singledispatch==3.4.0.3
six==1.10.0
tornado==4.3
update-checker==0.11

Not behind any proxy or VPN, own private internet connection.

**Comment by sftwninja** [comment]
Can you install this version of Python? https://www.python.org/downloads/release/python-2712/

The Google servers you're trying to hit use SNI to serve multiple certs off of the same IP address, and I have a feeling that the OpenSSL that ships with 2.7.9 (2014-12-10) may not be mature enough to correctly build the SNI cert chain.

**Comment by UnacceptableUse** [comment]
New error now:

Traceback (most recent call last):
  File "pokecli.py", line 37, in <module>
    from pgoapi import PGoApi
  File
"C:\Users\Peter\Documents\DOCUMENTS\Programs\PokeTrainer\pgoapi\__init__.py",
line 18, in <module>
    from pgoapi.pgoapi import PGoApi
  File
"C:\Users\Peter\Documents\DOCUMENTS\Programs\PokeTrainer\pgoapi\pgoapi.py",
line 42, in <module>
    from pgoapi.auth_google import AuthGoogle
  File
"C:\Users\Peter\Documents\DOCUMENTS\Programs\PokeTrainer\pgoapi\auth_google.py",
line 28, in <module>
    from gpsoauth import perform_master_login, perform_oauth
  File "C:\Python27\lib\site-packages\gpsoauth\__init__.py", line 4, in
<module>
    from . import google
  File "C:\Python27\lib\site-packages\gpsoauth\google.py", line 4, in
<module>
    from Cryptodome.PublicKey import RSA
  File "C:\Python27\lib\site-packages\Cryptodome\PublicKey\RSA.py", line
79, in <module>
    from Cryptodome.IO import PKCS8, PEM
  File "C:\Python27\lib\site-packages\Cryptodome\IO\PKCS8.py", line 73, in
<module>
    from Cryptodome.IO._PBES import PBES1, PBES2, PbesError
  File "C:\Python27\lib\site-packages\Cryptodome\IO\_PBES.py", line 44, in
<module>
    from Cryptodome.Cipher import DES, ARC2, DES3, AES
  File "C:\Python27\lib\site-packages\Cryptodome\Cipher\__init__.py", line
78, in <module>
    from Cryptodome.Cipher._mode_ecb import _create_ecb_cipher
  File "C:\Python27\lib\site-packages\Cryptodome\Cipher\_mode_ecb.py", line
46, in <module>
    """
  File "C:\Python27\lib\site-packages\Cryptodome\Util\_raw_api.py", line
168, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s'" % name)

**Comment by sftwninja** [comment]
If you installed the 64-bit version of Python, remove that and install the 32-bit version. I honestly didn't remember to mention that.

**Comment by UnacceptableUse** [comment]
Ah, yeah, my bad. I installed the 32bit version and it worked. Thanks!
