### ISSUE TITLE
Pokemon level is being set to None

### ISSUE THREAD

**Issue by spamfarm** [j-e-k/poketrainer#231]
```
2016-07-28 23:36:05,662 [    pgoapi] [ INFO] Incubating 5.0km egg, 3.46km done
2016-07-28 23:36:05,703 [   pokecli] [ERROR] Error in main loop, restarting %s
Traceback (most recent call last):
  File "pokecli.py", line 121, in main
    api.main_loop()
  File "/pgoapi/pgoapi.py", line 868, in main_loop
    self.spin_all_forts_visible()
  File "/pgoapi/pgoapi.py", line 408, in spin_all_forts_visible
    map(lambda x: "via:%f,%f" % (x[0]['latitude'], x[0]['longitude']), destinations[1:]))
  File "/pgoapi/pgoapi.py", line 312, in walk_to
    self.heartbeat()
  File "/pgoapi/pgoapi.py", line 256, in heartbeat
    self.cleanup_pokemon(self.inventory.inventory_items)
  File "/pgoapi/pgoapi.py", line 566, in cleanup_pokemon
    if self.is_pokemon_eligible_for_transfer(pokemon, sorted_pokemons[0]):
  File "/pgoapi/pgoapi.py", line 574, in is_pokemon_eligible_for_transfer
    self.pokemon_lvl(best_pokemon) * self.RELEASE_DUPLICATES_SCALER > self.pokemon_lvl(
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'











2016-07-28 23:36:39,856 [    pgoapi] [ INFO] Nearby Pokemon: Bulbasaur, Paras
2016-07-28 23:36:40,015 [    pgoapi] [ INFO] Trying initiate catching Pokemon: Nickname: , Type: Bulbasaur, CP: 0, IV: 0.0
2016-07-28 23:36:40,329 [    pgoapi] [ INFO] Couldn't catch Nickname: , Type: NA, CP: 0, IV: 0.0 Your pokemon bag was full, attempting to clear and re-try
2016-07-28 23:36:41,131 [    pgoapi] [ERROR] Error in pokemon encounter unsupported operand type(s) for *: 'NoneType' and 'float'
2016-07-28 23:36:46,581 [    pgoapi] [ INFO] Trying initiate catching Pokemon: Nickname: , Type: Paras, CP: 0, IV: 0.0
2016-07-28 23:36:46,796 [    pgoapi] [ INFO] Couldn't catch Nickname: , Type: NA, CP: 0, IV: 0.0 Your pokemon bag was full, attempting to clear and re-try
2016-07-28 23:36:46,954 [    pgoapi] [ERROR] Error in pokemon encounter unsupported operand type(s) for *: 'NoneType' and 'float'
2016-07-28 23:36:51,959 [    pgoapi] [ INFO] =================================
2016-07-28 23:36:52,479 [    pgoapi] [ INFO] Nearby Pokemon: Bulbasaur, Paras
2016-07-28 23:36:52,662 [    pgoapi] [ INFO] Trying initiate catching Pokemon: Nickname: , Type: Bulbasaur, CP: 0, IV: 0.0
2016-07-28 23:36:52,830 [    pgoapi] [ INFO] Couldn't catch Nickname: , Type: NA, CP: 0, IV: 0.0 Your pokemon bag was full, attempting to clear and re-try
2016-07-28 23:36:53,018 [    pgoapi] [ERROR] Error in pokemon encounter unsupported operand type(s) for *: 'NoneType' and 'float'
2016-07-28 23:36:58,170 [    pgoapi] [ INFO] Trying initiate catching Pokemon: Nickname: , Type: Paras, CP: 0, IV: 0.0
2016-07-28 23:36:58,350 [    pgoapi] [ INFO] Couldn't catch Nickname: , Type: NA, CP: 0, IV: 0.0 Your pokemon bag was full, attempting to clear and re-try
2016-07-28 23:36:58,704 [    pgoapi] [ERROR] Error in pokemon encounter unsupported operand type(s) for *: 'NoneType' and 'float'
```

**Comment by beeedy** [comment]
Can you paste your config?

**Comment by Jay1** [comment]
what beeedy said,  also you're bag is full of pokemons

**Comment by infinitewarp** [comment]
I think I may have fixed this recently in the develop branch. Are you still having this problem in the latest code?

**Comment by destiny117** [comment]
Seems to be fixed
