### ISSUE TITLE
Error in "items_awarded"

### ISSUE THREAD

**Issue by beeedy** [j-e-k/poketrainer#245]
```
Traceback (most recent call last):
  File "pokecli.py", line 121, in main
    api.main_loop()
  File "/home/broderick/pgoapi/pgoapi/pgoapi.py", line 947, in main_loop
    self.spin_near_fort()
  File "/home/broderick/pgoapi/pgoapi/pgoapi.py", line 501, in spin_near_fort
    self.walk_to_fort(fort_data)
  File "/home/broderick/pgoapi/pgoapi/pgoapi.py", line 484, in walk_to_fort
    self.fort_search_pgoapi(fort, self.get_position(), fort_data[1])
  File "/home/broderick/pgoapi/pgoapi/pgoapi.py", line 432, in fort_search_pgoapi
    for item in res['items_awarded']:
KeyError: 'items_awarded'

```

Wanted to post for any info that may be of use to the dev that has worked on this system

**Comment by sftwninja** [comment]
AFAIK, this should be solved by #175. Is this happening in the develop branch?

**Comment by beeedy** [comment]
This was in the most recent pull from development

**Comment by filpet** [comment]
Also happening with the latest master, which was working till a few hours ago.

**Comment by j-e-k** [comment]
Is it still not working?

**Comment by j-e-k** [comment]
Just added a quick hack to develop to address this. Please reopen if it is not working
