### ISSUE TITLE
I get this error on an account

### ISSUE THREAD

**Issue by TwoDCube** [j-e-k/poketrainer#269]
2016-07-29 21:55:41,640 [   pokecli] [ERROR$ Error in main loop, restarting %s
Traceback (most recent call last):
  File "pokecli.py", line 121, in main
    api.main_loop()
  File "/root/poketrainer/pgoapi/pgoapi.py"$ line 871, in main_loop
    self.spin_all_forts_visible()
  File "/root/poketrainer/pgoapi/pgoapi.py"$ line 411, in spin_all_forts_visible
    map(lambda x: "via:%f,%f" % (x[0]['lati$ude'], x[0]['longitude']), destinations[1:]))
  File "/root/poketrainer/pgoapi/pgoapi.py", line 312, in walk_to
    self.heartbeat()
  File "/root/poketrainer/pgoapi/pgoapi.py", line 254, in heartbeat
    self.incubate_eggs()
  File "/root/poketrainer/pgoapi/pgoapi.py", line 743, in incubate_eggs
    incubator_egg_distance = incubator['target_km_walked'] - incubator['start_km_walked']
KeyError: 'start_km_walked'

Then the bot restarts and throws this error again

**Comment by j-e-k** [comment]
This should be fixed on the develop branch

**Comment by j-e-k** [comment]
I cherry picked the commit to master. Should work now
