### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '/home/pokemon/poketrainer.GH/.listeners'

### ISSUE THREAD

**Issue by archeious** [j-e-k/poketrainer#271]
The socket is not getting  created.  I am not sure where to go from here.  

[2016-07-29 21:02:24,694] ERROR in app: Exception on /XXXXXXXX/pokemon [GET]
Traceback (most recent call last):
  File "/home/anaconda2/envs/py27/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/anaconda2/envs/py27/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/anaconda2/envs/py27/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/anaconda2/envs/py27/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/anaconda2/envs/py27/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "web.py", line 40, in inventory
    c = get_api_rpc(username)
  File "web.py", line 102, in get_api_rpc
    with open(desc_file) as f:
IOError: [Errno 2] No such file or directory: '/home/pokemon/poketrainer.GH/.listeners'
XXX.XXX.XXX.XXX - - [29/Jul/2016 21:02:24] "GET /XXXXXXXX/pokemon HTTP/1.1" 500 -

**Comment by j-e-k** [comment]
Should be fixed in dev
