### ISSUE TITLE
Error in disk encounter 0

### ISSUE THREAD

**Issue by infinitewarp** [j-e-k/poketrainer#286]
It looks like sometimes when we have a disc encounter where we are "At Fort with Lure AND Active Pokemon", the following error occurs:

```
2016-07-29 22:06:56,178 [    pgoapi] [ERROR] Error in disk encounter 0
```

I've added some logging locally and found that the cause is when the server returns a minimal JSON object without the keys we need:

```
2016-07-29 22:10:40,626 [    pgoapi] [ INFO] At Fort with Lure AND Active Pokemon Rattata
2016-07-29 22:10:41,008 [    pgoapi] [ INFO] {'result': 4}
2016-07-29 22:10:41,008 [    pgoapi] [ERROR] Error in disk encounter 0
Traceback (most recent call last):
  File "/Users/infinitewarp/Documents/code/poketrainer/pgoapi/pgoapi.py", line 789, in disk_encounter_pokemon
    pokemon = Pokemon(resp.get('pokemon_data', {}))
  File "/Users/infinitewarp/Documents/code/poketrainer/pgoapi/pokemon.py", line 69, in __init__
    additional_data = GAME_MASTER[self.pokemon_id]
KeyError: 0
```

I have an idea for a fix, and I'll create a pull request for it shortly.

**Comment by infinitewarp** [comment]
Looks like this fix works for me. Instead of errors, now I see a more appropriate message:

```
2016-07-29 22:26:12,233 [    pgoapi] [ INFO] At Fort with Lure AND Active Pokemon Pidgey
2016-07-29 22:26:12,604 [    pgoapi] [ INFO] Could not start Disk (lure) encounter for pokemon: Pidgey
2016-07-29 22:26:13,844 [    pgoapi] [ INFO] No nearby pokemon
```

We could add a more useful info message if anyone knows what result=4 really means, but at least this is better than before.

**Comment by j-e-k** [comment]
Great thanks
