### ISSUE TITLE
Error in pokemon encounter 0

### ISSUE THREAD

**Issue by infinitewarp** [j-e-k/poketrainer#291]
I seem to sometimes get this error, and I'm getting it consistently at the moment:

```
2016-07-30 02:06:52,920 [    pgoapi] [ INFO] Trying initiate catching Pokemon: Type: Pinsir CP: 0, IV: 0.00, Lvl: 0.0, LvlWild: 0.0, MaxCP: 52, Score: 0, IV-Norm.: 0
2016-07-30 02:06:53,213 [    pgoapi] [ERROR] Error in pokemon encounter 0
```

I've added some logging and found:
```
2016-07-30 02:10:24,500 [    pgoapi] [ INFO] Nearby Pokemon: Pinsir
2016-07-30 02:10:24,730 [    pgoapi] [ INFO] Trying initiate catching Pokemon: Type: Pinsir CP: 0, IV: 0.00, Lvl: 0.0, LvlWild: 0.0, MaxCP: 52, Score: 0, IV-Norm.: 0
2016-07-30 02:10:24,991 [    pgoapi] [ INFO] {'status': 7}
2016-07-30 02:10:24,991 [    pgoapi] [ERROR] Error in pokemon encounter 0
Traceback (most recent call last):
  File "/Users/infinitewarp/Documents/code/poketrainer/pgoapi/pgoapi.py", line 861, in encounter_pokemon
    pokemon = Pokemon(encounter.get('wild_pokemon', {}).get('pokemon_data', {}))
  File "/Users/infinitewarp/Documents/code/poketrainer/pgoapi/pokemon.py", line 69, in __init__
    additional_data = GAME_MASTER[self.pokemon_id]
KeyError: 0
```

Looks like a very similar problem to #286, and I suspect the fix will be similar. Will post a pull request shortly…

**Comment by infinitewarp** [comment]
Looks like this change fixed the issue for me:

```
2016-07-30 02:25:14,250 [    pgoapi] [ INFO] Nearby Pokemon: Rattata
2016-07-30 02:25:14,482 [    pgoapi] [ INFO] Trying initiate catching Pokemon: Type: Rattata CP: 0, IV: 0.00, Lvl: 0.0, LvlWild: 0.0, MaxCP: 12, Score: 0, IV-Norm.: 0
2016-07-30 02:25:14,741 [    pgoapi] [ INFO] Couldn't catch Rattata Your pokemon bag was full, attempting to clear and re-try
2016-07-30 02:25:15,229 [    pgoapi] [ INFO] Trying initiate catching Pokemon: Type: Rattata CP: 0, IV: 0.00, Lvl: 0.0, LvlWild: 0.0, MaxCP: 12, Score: 0, IV-Norm.: 0
2016-07-30 02:25:15,478 [    pgoapi] [ INFO] Couldn't catch Rattata Your pokemon bag was full, attempting to clear and re-try
2016-07-30 02:25:21,738 [    pgoapi] [ INFO] Traveled 183.13 meters of 183.13 of the trip
2016-07-30 02:25:21,738 [    pgoapi] [ INFO] ===============================================
2016-07-30 02:25:22,002 [    pgoapi] [ INFO] For spinned but Your inventory is full.
```

**Comment by j-e-k** [comment]
Great closing then
