### ISSUE TITLE
Error in disk encounter 'GET_INVENTORY'

### ISSUE THREAD

**Issue by infinitewarp** [j-e-k/poketrainer#292]
I'm seeing this randomly when running into disk encounters with a full item and pokémon bags.

```
2016-07-30 02:10:21,945 [    pgoapi] [ INFO] Fort spinned but Your inventory is full.
2016-07-30 02:10:22,175 [    pgoapi] [ INFO] At Fort with Lure AND Active Pokemon Rattata
2016-07-30 02:10:22,432 [    pgoapi] [ INFO] Couldn't catch Rattata Your pokemon bag was full, attempting to clear and re-try
2016-07-30 02:10:22,865 [    pgoapi] [ INFO] At Fort with Lure AND Active Pokemon Rattata
2016-07-30 02:10:23,110 [    pgoapi] [ INFO] Couldn't catch Rattata Your pokemon bag was full, attempting to clear and re-try
2016-07-30 02:10:23,280 [    pgoapi] [ERROR] Error in disk encounter 'GET_INVENTORY'
```

Looks like this is causing it:
```
Traceback (most recent call last):
  File "/Users/infinitewrap/Documents/code/poketrainer/pgoapi/pgoapi.py", line 806, in disk_encounter_pokemon
    self.cleanup_pokemon()
  File "/Users/infinitewrap/Documents/code/poketrainer/pgoapi/pgoapi.py", line 679, in cleanup_pokemon
    inventory_items = self.get_inventory().call()['responses']['GET_INVENTORY']['inventory_delta'][
KeyError: 'GET_INVENTORY'
```

We need to be still more defensive about accessing these dictionaries…

**Comment by cryzies** [comment]
What are you sleep timers, they recently throttled how many API calls you can make per second.

**Comment by destiny117** [comment]
#390 will make accessing these dictionaries more error resistent, please check and open new issue if you get another error now
