### ISSUE TITLE
 [ERROR] Error in main loop 'RECYCLE_INVENTORY_ITEM', 

### ISSUE THREAD

**Issue by HibikiFox** [j-e-k/poketrainer#316]
New error in loop

```
2016-07-30 17:57:48,737 [   pokecli] [ERROR] Error in main loop 'RECYCLE_INVENTORY_ITEM', restarting at location: (39.54720005679049, -104.99696992855397, 0)
Traceback (most recent call last):
  File "pokecli.py", line 158, in main
    api.main_loop()
  File "D:\%path%\Downloads\poketrainer-develop\poketrainer-develop\pgoapi\pgoapi.py", line 1006, in main_loop
    self.spin_all_forts_visible()
  File "D:\%path%\Downloads\poketrainer-develop\poketrainer-develop\pgoapi\pgoapi.py", line 491, in spin_all_forts_visible
    map(lambda x: "via:%f,%f" % (x[0]['latitude'], x[0]['longitude']), destinations[1:]))
  File "D:\%path%\Downloads\poketrainer-develop\poketrainer-develop\pgoapi\pgoapi.py", line 405, in walk_to
    self.spin_nearest_fort()
  File "D:\%path%\Downloads\poketrainer-develop\poketrainer-develop\pgoapi\pgoapi.py", line 431, in spin_nearest_fort
    self.walk_to_fort(destinations[0], directly=True)
  File "D:\%path%\Downloads\poketrainer-develop\poketrainer-develop\pgoapi\pgoapi.py", line 502, in walk_to_fort
    self.walk_to((fort['latitude'], fort['longitude']), directly=directly)
  File "D:\%path%\Downloads\poketrainer-develop\poketrainer-develop\pgoapi\pgoapi.py", line 401, in walk_to
    self.heartbeat()
  File "D:\%path%\Downloads\poketrainer-develop\poketrainer-develop\pgoapi\pgoapi.py", line 312, in heartbeat
    self.log.debug(self.cleanup_inventory(self.inventory.inventory_items))
  File "D:\%path%\Downloads\poketrainer-develop\poketrainer-develop\pgoapi\pgoapi.py", line 618, in cleanup_inventory
    'RECYCLE_INVENTORY_ITEM']
KeyError: 'RECYCLE_INVENTORY_ITEM'
```
ref #290

**Comment by destiny117** [comment]
#390 should handle this, closing for now
