### ISSUE TITLE
pokecli.py and web.py must *both* run on python2 or 3

### ISSUE THREAD

**Issue by infinitewarp** [j-e-k/poketrainer#324]
Not sure if this is an issue *we* want to deal with, but I've found that because of issues in zerorpc, you have to run *both* `pokecli.py` and `web.py` on either python2 or python3.

If you try running one of them on py2 and the other on py3, zerorpc fails to communicate with unspecified byte problems. Maybe this is just something we should throw into the README and say that we only support running both on the same version of Python.

Thoughts?

**Comment by rirze** [comment]
That's strange, cause discussions in zerorpc-python say they've fixed this issue:
https://github.com/0rpc/zerorpc-python/issues/108
https://github.com/0rpc/zerorpc-python/commit/d61b45e6bcd6989249c7349ed5766a6d986236cd

Is it an issue of a version requirement perhaps?

**Comment by infinitewarp** [comment]
Interesting.

For reference, when I run `python2 pokecli.py -i 1` and `python3 web.py` and try to load one of the web pages, the cli says:

```
2016-07-31 00:23:56,739 [   channel] [WARNING] zerorpc.ChannelMultiplexer, unable to route event: <'\x00\xcao\xd2\x8a'> _zpc_hb {'response_to': '056867b5176842eea731c9f6665af575', 'message_id': '056867b6176842eea731c9f6665af575', 'v': 3} [...]
```

and in the browser the web response says:
```
zerorpc.exceptions.LostRemote
zerorpc.exceptions.LostRemote: Lost remote after 10s heartbeat
```
followed by the same stack trace that the web script says to stdout:
```
zerorpc.ChannelMultiplexer, unable to route event: <b''> OK {'message_id': 'fa87f484-bfdc-4e26-8b94-3eafa5c65640', 'v': 3, 'response_to': '056867b5176842eea731c9f6665af575'} [...]
127.0.0.1 - - [31/Jul/2016 00:24:06] "GET /[redacted] HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/infinitewarp/.envs/poketrainer3/lib/python3.5/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/infinitewarp/.envs/poketrainer3/lib/python3.5/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/infinitewarp/.envs/poketrainer3/lib/python3.5/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/infinitewarp/.envs/poketrainer3/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/infinitewarp/.envs/poketrainer3/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/infinitewarp/.envs/poketrainer3/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/infinitewarp/.envs/poketrainer3/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/infinitewarp/.envs/poketrainer3/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/infinitewarp/.envs/poketrainer3/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/infinitewarp/.envs/poketrainer3/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/infinitewarp/Documents/code/poketrainer/web.py", line 67, in status
    latlng = c.current_location()
  File "/Users/infinitewarp/.envs/poketrainer3/src/zerorpc/zerorpc/core.py", line 278, in <lambda>
    return lambda *args, **kargs: self(method, *args, **kargs)
  File "/Users/infinitewarp/.envs/poketrainer3/src/zerorpc/zerorpc/core.py", line 270, in __call__
    return self._process_response(request_event, bufchan, timeout)
  File "/Users/infinitewarp/.envs/poketrainer3/src/zerorpc/zerorpc/core.py", line 227, in _process_response
    reply_event = bufchan.recv(timeout=timeout)
  File "/Users/infinitewarp/.envs/poketrainer3/src/zerorpc/zerorpc/channel.py", line 255, in recv
    event = self._input_queue.get(timeout=timeout)
  File "/Users/infinitewarp/.envs/poketrainer3/lib/python3.5/site-packages/gevent/queue.py", line 284, in get
    return self.__get_or_peek(self._get, block, timeout)
  File "/Users/infinitewarp/.envs/poketrainer3/lib/python3.5/site-packages/gevent/queue.py", line 261, in __get_or_peek
    result = waiter.get()
  File "/Users/infinitewarp/.envs/poketrainer3/lib/python3.5/site-packages/gevent/hub.py", line 878, in get
    return self.hub.switch()
  File "/Users/infinitewarp/.envs/poketrainer3/lib/python3.5/site-packages/gevent/hub.py", line 609, in switch
    return greenlet.switch(self)
zerorpc.exceptions.LostRemote: Lost remote after 10s heartbeat
```

**Comment by rirze** [comment]
Yah this seems completely out of our hands:
https://github.com/0rpc/zerorpc-python/issues/37
https://github.com/0rpc/zerorpc-python/issues/128

This is an active bug that they never got around to fixing...
Your idea to warn users of this problem is probably the better approach to this issue.

**Comment by infinitewarp** [comment]
That pull request adds some relevant notes to our README and tells users to pick one version of Python.

**Comment by j-e-k** [comment]
agreed!
