### ISSUE TITLE
python3: Error in main loop unorderable types

### ISSUE THREAD

**Issue by infinitewarp** [j-e-k/poketrainer#325]
I try running the same account in the same branch on python2, and it works just fine. Looks like a python3-specific issue in `is_pokemon_eligible_for_evolution`:

```
2016-07-31 00:16:15,094 [    pgoapi] [ INFO] Incubating 10.0km egg, 3.92km done
2016-07-31 00:16:15,105 [   pokecli] [ERROR] Error in main loop unorderable types: int() > NoneType(), restarting at location: ([redacted], 0)
Traceback (most recent call last):
  File "pokecli.py", line 162, in main
    api.main_loop()
  File "/Users/infinitewarp/Documents/code/poketrainer/pgoapi/pgoapi.py", line 1134, in main_loop
    self.spin_all_forts_visible()
  File "/Users/infinitewarp/Documents/code/poketrainer/pgoapi/pgoapi.py", line 596, in spin_all_forts_visible
    map(lambda x: "via:%f,%f" % (x[0]['latitude'], x[0]['longitude']), destinations[1:]))
  File "/Users/infinitewarp/Documents/code/poketrainer/pgoapi/pgoapi.py", line 505, in walk_to
    self.heartbeat()
  File "/Users/infinitewarp/Documents/code/poketrainer/pgoapi/pgoapi.py", line 420, in heartbeat
    self.attempt_evolve(self.inventory.inventory_items)
  File "/Users/infinitewarp/Documents/code/poketrainer/pgoapi/pgoapi.py", line 865, in attempt_evolve
    if not self.attempt_evolve_pokemon(pokemon):
  File "/Users/infinitewarp/Documents/code/poketrainer/pgoapi/pgoapi.py", line 869, in attempt_evolve_pokemon
    if self.is_pokemon_eligible_for_evolution(pokemon=pokemon):
  File "/Users/infinitewarp/Documents/code/poketrainer/pgoapi/pgoapi.py", line 894, in is_pokemon_eligible_for_evolution
    return candy_have > candy_needed and \
TypeError: unorderable types: int() > NoneType()
```

I think I know the cause of this, and I'll open a pull request shortly…

**Comment by infinitewarp** [comment]
Specifically, it looks like this happens whenever the bot wants to check a pokemon type for evolution, but that pokemon type doesn't have the config set in POKEMON_EVOLUTION.

Apparently py2 is happy to try a `>` check on an `int` to `None`, but py3 isn't.
