### ISSUE TITLE
[Web.py][ERROR] LostRemote: Lost remote after 10s heartbeat

### ISSUE THREAD

**Issue by zatipnis** [j-e-k/poketrainer#401]
_Web.py_ fails to load for correct usernames (shows proper error messages for 404 and wrong username).

**Error:**
**`LostRemote: Lost remote after 10s heartbeat`**

`Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/zatipnis/Projects/Pokemon/poketrainer2/web.py", line 67, in status
    latlng = c.current_location()
  File "/usr/local/lib/python2.7/site-packages/zerorpc-0.5.2-py2.7.egg/zerorpc/core.py", line 257, in <lambda>
    return lambda *args, **kargs: self(method, *args, **kargs)
  File "/usr/local/lib/python2.7/site-packages/zerorpc-0.5.2-py2.7.egg/zerorpc/core.py", line 249, in __call__
    return self._process_response(request_event, bufchan, timeout)
  File "/usr/local/lib/python2.7/site-packages/zerorpc-0.5.2-py2.7.egg/zerorpc/core.py", line 223, in _process_response
    reply_event = bufchan.recv(timeout=timeout)
  File "/usr/local/lib/python2.7/site-packages/zerorpc-0.5.2-py2.7.egg/zerorpc/channel.py", line 253, in recv
    event = self._input_queue.get(timeout=timeout)
  File "/usr/local/lib/python2.7/site-packages/gevent-1.1.2-py2.7-macosx-10.11-x86_64.egg/gevent/queue.py", line 284, in get
    return self.__get_or_peek(self._get, block, timeout)
  File "/usr/local/lib/python2.7/site-packages/gevent-1.1.2-py2.7-macosx-10.11-x86_64.egg/gevent/queue.py", line 261, in __get_or_peek
    result = waiter.get()
  File "/usr/local/lib/python2.7/site-packages/gevent-1.1.2-py2.7-macosx-10.11-x86_64.egg/gevent/hub.py", line 878, in get
    return self.hub.switch()
  File "/usr/local/lib/python2.7/site-packages/gevent-1.1.2-py2.7-macosx-10.11-x86_64.egg/gevent/hub.py", line 609, in switch
    return greenlet.switch(self)`

**Comment by rhythem** [comment]
I get the same Error!!

**Comment by Abdess** [comment]
Same error with the develop branch on Ubuntu 14.04 in virtualenv

**Comment by catechumen27** [comment]
Make that three.

**Comment by rhythem** [comment]
@infinitewarp any support on tis issue?

**Comment by infinitewarp** [comment]
Unfortunately, I won't be looking at this until we have the bot itself actually working. In case you missed the news, Niantic changed the API today and that's broken all bots including ours. See also https://github.com/j-e-k/poketrainer/issues/414

**Comment by rhythem** [comment]
Ye, it looks like i posted this just a few moments before niantic upped the game!! ATB Devs.

**Comment by haver007** [comment]
Well like to push it a bit. Because its anoying... without :D Well I'm a programmer for C# C++ so if I can help just ask ;)
