### ISSUE TITLE
Traceback during inventory cleanup

### ISSUE THREAD

**Issue by HousewifeHacker** [j-e-k/poketrainer#412]
`Traceback (most recent call last):
  File "pokecli.py", line 162, in main
    api.main_loop()
  File "/Users/HH/pokemon/poketrainer/pgoapi/pgoapi.py", line 1163, in main_loop
    self.spin_near_fort()
  File "/Users/HH/pokemon/poketrainer/pgoapi/pgoapi.py", line 630, in spin_near_fort
    self.walk_back_to_origin()
  File "/Users/HH/pokemon/poketrainer/pgoapi/pgoapi.py", line 525, in walk_back_to_origin
    self.walk_to(self._origPosF)
  File "/Users/HH/pokemon/poketrainer/pgoapi/pgoapi.py", line 509, in walk_to
    self.heartbeat()
  File "/Users/HH/pokemon/poketrainer/pgoapi/pgoapi.py", line 419, in heartbeat
    self.log.debug(self.cleanup_inventory(self.inventory.inventory_items))
  File "/Users/HH/pokemon/poketrainer/pgoapi/pgoapi.py", line 743, in cleanup_inventory
    response_code = res['result']
KeyError: 'result'
`

Looks like the actual error is the line above it
`res = self.recycle_inventory_item(item_id=item['item_id'], count=recycle_count).call()['responses']['RECYCLE_INVENTORY_ITEM']`

**Comment by infinitewarp** [comment]
This issue appears to already be fixed in the develop branch, but we haven't merged that fix into a release build yet. (It looks like you're using either a release build or the master branch.)

If you keep encountering this problem, you should try downloading a recent copy of [the develop branch](https://github.com/j-e-k/poketrainer/tree/develop) and running with that.
