### ISSUE TITLE
encrypt.dll/libencrypt.so 

### ISSUE THREAD

**Issue by j-e-k** [j-e-k/poketrainer#418]
So these files probably can't be distributed with this repository, but they are required for it to work. Any ideas?

**Comment by HibikiFox** [comment]
Can you add a Rar ? or a zip?

**Comment by j-e-k** [comment]
pastebin/jw149TkT

😉

**Comment by skydrome** [comment]
can report its working here, thanks

**Comment by josephbedminster** [comment]
Nice, works for me too,
Thanks

**Comment by rhythem** [comment]
what do we do after downloading the crypt file??? @j-e-k

**Comment by josephbedminster** [comment]
@rhythem put it in your poke trainer folder and run the client with :
```sh
python pokecli.py -i ACCOUNT_INDEx -e YOUR_ENCRYPT_LIB_NAME_GOES_HERE.DLL.SO
```

**Comment by rhythem** [comment]
done that:
```
rhythem:~/workspace/poketrainer (master) $ python pokecli.py -i 0 -e libencrypt.so
2016-08-07 08:53:24,392 [   pokecli] [ INFO] Your given location: Southern Pacific Railroad, Los Angeles, CA 90021, USA
2016-08-07 08:53:24,392 [   pokecli] [ INFO] lat/long/alt: 34.0304056 -118.2394284 0.0
2016-08-07 08:53:24,395 [auth_google] [ INFO] Google User Login for: amit7493@gmail.com
2016-08-07 08:53:24,877 [auth_google] [ INFO] Google User Login successful.
2016-08-07 08:53:24,877 [auth_google] [ INFO] Request Google Access Token...
2016-08-07 08:53:24,941 [auth_google] [ INFO] Google Access Token successfully received.
2016-08-07 08:53:24,941 [    pgoapi] [ INFO] Starting RPC login sequence (app simulation)
Traceback (most recent call last):
  File "pokecli.py", line 179, in <module>
    main()
  File "pokecli.py", line 159, in main
    while not api.login(config["auth_service"], config["username"], config["password"]):
  File "/home/ubuntu/workspace/poketrainer/pgoapi/pgoapi.py", line 1153, in login
    response = self.call()
  File "/home/ubuntu/workspace/poketrainer/pgoapi/pgoapi.py", line 261, in call
    request.activate_signature(self.get_signature_lib())
  File "/home/ubuntu/workspace/poketrainer/pgoapi/rpc_api.py", line 86, in activate_signature
    ctypes.cdll.LoadLibrary(lib_path)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libencrypt.so: cannot open shared object file: No such file or directory

```

**Comment by Korndaweizen** [comment]
same error here...

**Comment by rhythem** [comment]
Run this command on the system you gonna run the script.
wget http://pgoapi.com/pgoencrypt.tar.gz && tar -xf pgoencrypt.tar.gz && cd pgoencrypt/src/ && make

After that copy the libencrypt.so to your bot directory and rename it to encrypt.so.
This file is different for each system so recreate when ever you switch systems.

**Comment by infinitewarp** [comment]
Thanks for the notes @rhythem !

Also, we've created a new catch-all for encrypt issues here: https://github.com/j-e-k/poketrainer/issues/436
