### ISSUE TITLE
Sorry but how to build a encrypt library

### ISSUE THREAD

**Issue by IllidanU** [j-e-k/poketrainer#425]
"finding the c_code folder of one of the unknown6 repositories"

Does that means I should look for a folder named "c-code"? I didn't find one in my computer.

Sorry I don't get it.

**Comment by BoBeR182** [comment]
https://www.sendspace.com/file/zt6ddo

**Comment by rhythem** [comment]
where do i put this file? @BoBeR182

**Comment by cybertim** [comment]
it's clearly written in the README, use the -e flag

**Comment by rhythem** [comment]
i am doing that, gives me error

```
rhythem:~/workspace/poketrainer (master) $ python pokecli.py -i 0 -e libencrypt.so
2016-08-07 08:53:24,392 [   pokecli] [ INFO] Your given location: Southern Pacific Railroad, Los Angeles, CA 90021, USA
2016-08-07 08:53:24,392 [   pokecli] [ INFO] lat/long/alt: 34.0304056 -118.2394284 0.0
2016-08-07 08:53:24,395 [auth_google] [ INFO] Google User Login for: amit7493@gmail.com
2016-08-07 08:53:24,877 [auth_google] [ INFO] Google User Login successful.
2016-08-07 08:53:24,877 [auth_google] [ INFO] Request Google Access Token...
2016-08-07 08:53:24,941 [auth_google] [ INFO] Google Access Token successfully received.
2016-08-07 08:53:24,941 [    pgoapi] [ INFO] Starting RPC login sequence (app simulation)
Traceback (most recent call last):
  File "pokecli.py", line 179, in <module>
    main()
  File "pokecli.py", line 159, in main
    while not api.login(config["auth_service"], config["username"], config["password"]):
  File "/home/ubuntu/workspace/poketrainer/pgoapi/pgoapi.py", line 1153, in login
    response = self.call()
  File "/home/ubuntu/workspace/poketrainer/pgoapi/pgoapi.py", line 261, in call
    request.activate_signature(self.get_signature_lib())
  File "/home/ubuntu/workspace/poketrainer/pgoapi/rpc_api.py", line 86, in activate_signature
    ctypes.cdll.LoadLibrary(lib_path)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libencrypt.so: cannot open shared object file: No such file or directory
```

**Comment by BoBeR182** [comment]
`python pokecli.py -i 0 -e ./libencrypt.so`

**Comment by rhythem** [comment]
Something diffrent this time

```
rhythem:~/workspace/poketrainer (master) $ python pokecli.py -i 0 -e ./libencrypt.so
2016-08-07 09:52:35,902 [   pokecli] [ INFO] Your given location: Southern Pacific Railroad, Los Angeles, CA 90021, USA
2016-08-07 09:52:35,903 [   pokecli] [ INFO] lat/long/alt: 34.0304056 -118.2394284 0.0
2016-08-07 09:52:35,906 [auth_google] [ INFO] Google User Login for: amit7493@gmail.com
2016-08-07 09:52:36,326 [auth_google] [ INFO] Google User Login successful.
2016-08-07 09:52:36,326 [auth_google] [ INFO] Request Google Access Token...
2016-08-07 09:52:36,458 [auth_google] [ INFO] Google Access Token successfully received.
2016-08-07 09:52:36,458 [    pgoapi] [ INFO] Starting RPC login sequence (app simulation)
Traceback (most recent call last):
  File "pokecli.py", line 179, in <module>
    main()
  File "pokecli.py", line 159, in main
    while not api.login(config["auth_service"], config["username"], config["password"]):
  File "/home/ubuntu/workspace/poketrainer/pgoapi/pgoapi.py", line 1153, in login
    response = self.call()
  File "/home/ubuntu/workspace/poketrainer/pgoapi/pgoapi.py", line 261, in call
    request.activate_signature(self.get_signature_lib())
  File "/home/ubuntu/workspace/poketrainer/pgoapi/rpc_api.py", line 86, in activate_signature
    ctypes.cdll.LoadLibrary(lib_path)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ./libencrypt.so: invalid ELF header
```

**Comment by BoBeR182** [comment]
Compile libencrypt.so yourself, our system architecture must be different.

**Comment by rhythem** [comment]
wget http://pgoapi.com/pgoencrypt.tar.gz && tar -xf pgoencrypt.tar.gz && cd pgoencrypt/src/ && make

A general command for all people i found online!!

**Comment by IllidanU** [comment]
Thank you all
