### ISSUE TITLE
libencrypt.so unknown file type

### ISSUE THREAD

**Issue by Idhanta** [j-e-k/poketrainer#426]
2016-08-07 14:18:45,344 [    pgoapi] [ INFO] Starting RPC login sequence (app simulation)
Traceback (most recent call last):
  File "pokecli.py", line 179, in <module>
    main()
  File "pokecli.py", line 159, in main
    while not api.login(config["auth_service"], config["username"], config["password"]):
  File "/Users/idhanta/Desktop/poketrainer-master/pgoapi/pgoapi.py", line 1153, in login
    response = self.call()
  File "/Users/idhanta/Desktop/poketrainer-master/pgoapi/pgoapi.py", line 261, in call
    request.activate_signature(self.get_signature_lib())
  File "/Users/idhanta/Desktop/poketrainer-master/pgoapi/rpc_api.py", line 86, in activate_signature
    ctypes.cdll.LoadLibrary(lib_path)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(libencrypt.so, 6): no suitable image found.  Did find:
	libencrypt.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00

**Comment by BoBeR182** [comment]
Why are you using a linux libencrypt.so instead of a windows encrypt.dll?

**Comment by Idhanta** [comment]
Yeah, just saw that. Fixed it, my bad.

**Comment by j-e-k** [comment]
Glad you got it working :)
