### ISSUE TITLE
Encrypt.dll or lybencryot.so

### ISSUE THREAD

**Issue by titou15130** [j-e-k/poketrainer#432]
Sorry by advance but i don't understand what we have to do with these files and how we make it.
I'm on ubuntu. 

Thank's.

**Comment by lordskylare** [comment]
pastebin/jw149TkT

**Comment by kwkroll32** [comment]
When I ran pokecli.py on Ubuntu 16.04, python threw an error about libencrypt.so not being found. I did have libcrypt.so instead, so I made a symlink from libcrypt.so named libencrypt.so and it seems to have worked.

**Comment by titou15130** [comment]
i generated the libencrypt.so and rename it to encryt.so before moving it in the bot directory

`root@tthis-VirtualBox:/home/tthis/Bureau/poketrainer# ls
compile_proto.sh              listener.pyc         requirements.txt
config.json                   MANIFEST.in          setup.py
container                     pgoapi               src
data_dumps                    pgoencrypt           static
encrypt.so                    PoGoPokeLvl.tsv      templates
GAME_ATTACKS_v0_1.tsv         pokecli.py           tests
GAME_MASTER_POKEMON_v0_2.tsv  pokemon.en.json      tox.ini
LICENSE.txt                   README.md            web_config.json.example
listener.py                   requirements-ci.txt  web.py`

`root@tthis-VirtualBox:/home/tthis/Bureau/poketrainer# python pokecli.py -i 0 -e encrypt.so 
2016-08-07 15:46:44,460 [   pokecli] [ INFO] Your given location: Avenue Gambetta, 15000 Aurillac, France
2016-08-07 15:46:44,460 [   pokecli] [ INFO] lat/long/alt: 44.927473 2.4454657 0.0
2016-08-07 15:46:44,462 [auth_google] [ INFO] Google User Login for: matthisgournay@gmail.com
2016-08-07 15:46:45,446 [auth_google] [ INFO] Google User Login successful.
2016-08-07 15:46:45,446 [auth_google] [ INFO] Request Google Access Token...
2016-08-07 15:46:45,739 [auth_google] [ INFO] Google Access Token successfully received.
2016-08-07 15:46:45,739 [    pgoapi] [ INFO] Starting RPC login sequence (app simulation)
Traceback (most recent call last):
  File "pokecli.py", line 179, in <module>
    main()
  File "pokecli.py", line 159, in main
    while not api.login(config["auth_service"], config["username"], config["password"]):
  File "/home/tthis/Bureau/poketrainer/pgoapi/pgoapi.py", line 1153, in login
    response = self.call()
  File "/home/tthis/Bureau/poketrainer/pgoapi/pgoapi.py", line 261, in call
    request.activate_signature(self.get_signature_lib())
  File "/home/tthis/Bureau/poketrainer/pgoapi/rpc_api.py", line 86, in activate_signature
    ctypes.cdll.LoadLibrary(lib_path)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: encrypt.so: cannot open shared object file: No such file or directory
`

**Comment by j-e-k** [comment]
Are you specifying `-e` to give it the path to the encrypt lib? You might need to use `-e ./encrypt.so` or some variety of that

**Comment by titou15130** [comment]
Thank's i m stupid -_- ''
