### ISSUE TITLE
[develop] poketrainer.py - TypeError: __init__() takes exactly 2 arguments (1 given)

### ISSUE THREAD

**Issue by mtuuu** [j-e-k/poketrainer#481]
attempting to start the latest develop branch gives me an error about not being able to find `GAME_MASTER_POKEMON_v0_2.tsv`, then `PoGoPokeLvl.tsv`, and finally `pokemon.en.json`. I symlinked these files from the /resources/ subdirectory back out to the root and this error went away, however now I get:

> `Traceback (most recent call last):
>   File "pokecli.py", line 83, in <module>
>     main()
>   File "pokecli.py", line 70, in main
>     poketrainer = Poketrainer(args)
>   File "/store/Dropbox/pgo/poketrainer/poketrainer/poketrainer.py", line 76, in __init__
>     self._load_api()
>   File "/store/Dropbox/pgo/poketrainer/poketrainer/poketrainer.py", line 152, in _load_api
>     self.api = api.pgoapi.PGoApi()
> TypeError: __init__() takes exactly 2 arguments (1 given)`

**Comment by mtuuu** [comment]
Re-cloned repo and copied configs. Working okay now.
