### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by omlet05** [j-e-k/poketrainer#490]
Hi, 
I'm on lastest dev, here is my status page.

```
UnicodeDecodeError
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 11: ordinal not in range(128)

Traceback (most recent call last)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2000, in __call__
return self.wsgi_app(environ, start_response)
File "/home/omlet/poketrainer/poketrainer/web.py", line 33, in __call__
return self.app(environ, start_response)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1991, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1567, in handle_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/home/omlet/poketrainer/poketrainer/web.py", line 186, in status
return render_template('status.html', pokemons=pokemons, player=player, currency="{:,d}".format(currency), candy=candy, latlng=latlng, attacks=attacks, username=username, options=options)
File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 134, in render_template
context, ctx.app)
File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 116, in _render
rv = template.render(context)
File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render
return self.environment.handle_exception(exc_info, True)
File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 754, in handle_exception
reraise(exc_type, exc_value, tb)
File "/home/omlet/poketrainer/poketrainer/templates/status.html", line 1, in top-level template code
{% extends "layout.html" %}
File "/home/omlet/poketrainer/poketrainer/templates/layout.html", line 56, in top-level template code
{% block content %}{% endblock content %}
File "/home/omlet/poketrainer/poketrainer/templates/status.html", line 67, in block "content"
<td style="{{options["ignore_name"]}}">{{pokemon.name}}</td>
File "/usr/local/lib/python2.7/dist-packages/markupsafe/_native.py", line 22, in escape
return Markup(text_type(s)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 11: ordinal not in range(128)
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.
```

here's full output error: https://gist.github.com/omlet05/a10348063443a60383c80b2ca9ad6077

thanks a lot ! 

Regards,

**Comment by rirze** [comment]
Seems related to http://stackoverflow.com/questions/21393758/unicodedecodeerror-ascii-codec-cant-decode-byte-0xe5-in-position-0-ordinal 

Somewhere strings not being read in as Unicode and it's throwing this error.

**Comment by j-e-k** [comment]
I will take a look, should be a quick fix

**Comment by infinitewarp** [comment]
@omlet05 Do you have any pokémon with custom names that have non-Latin (i.e. A-Z, a-z, 0-9) characters? Characters with accents or diacritic marks? Or perhaps emoji in the names?

**Comment by infinitewarp** [comment]
I was able to reproduce this by renaming one of my pokémon to "Blast¿ñ¥§₽". Working on a fix now.

**Comment by infinitewarp** [comment]
Should be working in the develop branch now if you stick with Python 2.

(Python 3 I haven't been able to verify yet because of https://github.com/j-e-k/poketrainer/issues/501)
