### ISSUE TITLE
python3: web.py: TypeError: 'filter' object is not subscriptable

### ISSUE THREAD

**Issue by infinitewarp** [j-e-k/poketrainer#503]
More python3 brokenness. 😖 

```
Traceback (most recent call last):
  File "/Users/infinitewarp/.envs/poketrainer3/lib/python3.5/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/infinitewarp/Documents/code/poketrainer/web.py", line 33, in __call__
    return self.app(environ, start_response)
  File "/Users/infinitewarp/.envs/poketrainer3/lib/python3.5/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/infinitewarp/.envs/poketrainer3/lib/python3.5/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/infinitewarp/.envs/poketrainer3/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/infinitewarp/.envs/poketrainer3/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/infinitewarp/.envs/poketrainer3/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/infinitewarp/.envs/poketrainer3/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/infinitewarp/.envs/poketrainer3/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/infinitewarp/.envs/poketrainer3/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/infinitewarp/.envs/poketrainer3/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/infinitewarp/Documents/code/poketrainer/web.py", line 152, in status
    config = init_config(username)
  File "/Users/infinitewarp/Documents/code/poketrainer/web.py", line 58, in init_config
    return filtered_data[0]
TypeError: 'filter' object is not subscriptable
```

**Comment by infinitewarp** [comment]
I have a fix ready for that specific issue, but it's useless because there are tons of other python3 incompatibilities in the current develop branch. I'm just going to hold my commit until I have all these py3 blockers fixed.
