### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by Lolwa18** [j-e-k/poketrainer#515]
How do I fix this:

Traceback (most recent call last):
  File "pokecli.py", line 46, in <module>
    from pgoapi import PGoApi
  File "C:\Users\Atharv Johri\Downloads\poketrainer-autosnipe (1)\poketrainer-autosnipe\pgoapi\__init__.py", line 19, in <module>
    from pgoapi.pgoapi import PGoApi  # noqa
  File "C:\Users\Atharv Johri\Downloads\poketrainer-autosnipe (1)\poketrainer-autosnipe\pgoapi\pgoapi.py", line 71
    <<<<<<< HEAD
     ^
SyntaxError: invalid syntax

**Comment by rirze** [comment]
lol it seems like a merge process didn't exactly go well....

What did you download and where did you get it from?

**Comment by j-e-k** [comment]
The auto snipe branch is going to be deleted shortly and setup anew with a socket based approach
